### ISSUE TITLE
Make it so user can specify how recent recommendations are allowed to be.

### ISSUE THREAD

**Issue by apc53c** [stewcraig/recommender#8]
Default to 1960 might be good.

**Comment by stewcraig** [comment]
Added text boxes to allow user to select year range of movie selection. Details of year range passed through to ajax get request.

Back end to be updated to return only recommendations that fall within request range only.

**Comment by apc53c** [comment]
I've created a separate issue for the backend part, so this can be closed.

**Comment by apc53c** [comment]
I think there should be a plus between 'minYear' and the year, and likewise for 'maxYear' and the year.  At the moment there doesn't seem to be a separator.
